import * as fs from 'fs';
import { ParsedTest } from '../types';
import { manipulateSwagger } from './helpers';
import { SwaggerDocs300 } from './index.types';

const defaultConfig = {
  info: {
    version: '1.0.0',
    title: 'Superdocs',
    description:
      'API docs generated by Superdocs',
    termsOfService: 'https://github.com/gutioliveira/superdocs',
    contact: {
      name: 'Superdocs',
      email: 'superdocs@superdocs.com',
      url: 'http://superdocs.com',
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/license/mit/',
    },
  },
  servers: [
    {
      url: 'http://localhost:3000',
    },
  ],
}

export const generateSwaggerDocs300 = (path: string, config?: SwaggerDocs300): string => {
  const info = fs.readFileSync(path, 'utf8');
  const docs = JSON.parse(info);
  const swagger: any = {
    openapi: '3.0.0',
    ...defaultConfig,
    paths: {},
    ...config
  };
  docs.forEach((doc: ParsedTest) => {
    manipulateSwagger(swagger, doc);
  });
  fs.writeFileSync(path, JSON.stringify(swagger));
  return JSON.stringify(swagger);
};